language: python
sudo: false
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install .

# command to run tests
script: coverage run --source pyjavaprops setup.py test

after_success:
  coveralls