language: python
sudo: false
python:
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install .

# command to run tests
script: coverage run --source pyjavaprops setup.py test

after_success:
  coveralls